# Generated by Django 4.2.15 on 2024-08-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0047_alter_ipaddress_role_alter_ipaddress_status_and_more"),
        ("dcim", "0062_module_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="vlan_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="devices",
                to="ipam.vlangroup",
            ),
        ),
    ]
