# Generated by Django 4.2.19 on 2025-02-10 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0067_controllermanageddevicegroup_tenant"),
        ("dcim", "0063_device_vlan_group"),
    ]

    operations = []
